"""empty message

Revision ID: 1b670d404a21
Revises: f81c1096b46a
Create Date: 2022-05-20 15:11:06.152056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b670d404a21'
down_revision = 'f81c1096b46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('puzzle', 'date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('puzzle', 'date',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
