"""empty message

Revision ID: 20270b21c447
Revises: 9bfc8af03a8c
Create Date: 2022-05-20 15:13:06.865041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20270b21c447'
down_revision = '9bfc8af03a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('puzzle', 'date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('puzzle', 'date',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
