"""updated puzzle table

Revision ID: 33581aac0ac6
Revises: bd497f48844b
Create Date: 2022-05-20 11:35:45.245927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33581aac0ac6'
down_revision = 'bd497f48844b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('puzzle', 'date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('puzzle', 'date',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
