"""empty message

Revision ID: d3637d4fbedd
Revises: 1b670d404a21
Create Date: 2022-05-20 15:19:08.778016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3637d4fbedd'
down_revision = '1b670d404a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('puzzle', 'date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('puzzle', 'date',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
